name: Tailscale - Docker

on:
  workflow_dispatch:
    inputs:
      link_iso:
        description: 'Dán link iso của ae vô đây'
        required: true
  # Cho phép nhận lệnh tự kích hoạt từ chính nó
  repository_dispatch:
    types: [rerun_event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install wget curl -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          sudo mkdir -p /isos/
          
          # Xác định link ISO (lấy từ nút bấm hoặc từ lần chạy trước truyền sang)
          LINK_ISO="${{ github.event.inputs.link_iso || github.event.client_payload.link_iso }}"
          
          # Tải ISO và Driver
          sudo wget -O /isos/a.iso "$LINK_ISO" &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          
          sudo wget -O /isos/driver.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win-0.1.240.iso &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          
          # Tải file cấu hình Docker
          wget https://raw.githubusercontent.com/socaca/buluxury/refs/heads/main/compose.yaml
          
          # Hiển thị IP để kết nối
          tailscale ip -4
          echo "Thành công! Kết nối bằng port 8006 ở trình duyệt Chrome."
          
          # Chạy Docker ngầm (-d)
          sudo docker compose up -d
          
          # Treo máy trong 5 tiếng 55 phút (355 phút)
          echo "Đang treo máy... Sẽ tự động khởi tạo lại sau 5h55m."
          sleep 355m 

      - name: Tự động kích hoạt lượt chạy tiếp theo
        if: always()
        run: |
          # Lấy lại link ISO để truyền sang lượt chạy sau
          LINK_ISO="${{ github.event.inputs.link_iso || github.event.client_payload.link_iso }}"
          
          # Gửi lệnh cho GitHub tạo một Action mới (Cần có MY_TOKEN trong Secrets)
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d "{\"event_type\": \"rerun_event\", \"client_payload\": {\"link_iso\": \"$LINK_ISO\"}}"
